#########################################
### Spring Cloud Config Server
#########################################
spring:
  cloud:
    config:
      server:
        composite:
          - type: git
            searchPaths: '{application}'